/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`learning_object_dates_show_for_courses`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesShowForCoursesError {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_show_for_courses2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesShowForCourses2Error {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_show_for_courses3`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesShowForCourses3Error {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_show_for_courses4`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesShowForCourses4Error {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_show_for_courses5`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesShowForCourses5Error {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_show_for_courses6`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesShowForCourses6Error {
    DefaultResponse(String),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_update_for_courses`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesUpdateForCoursesError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_update_for_courses2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesUpdateForCourses2Error {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_update_for_courses3`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesUpdateForCourses3Error {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_update_for_courses4`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesUpdateForCourses4Error {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`learning_object_dates_update_for_courses5`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LearningObjectDatesUpdateForCourses5Error {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}


/// Get a learning object's date-related information, including due date, availability dates, override status, and a paginated list of all assignment overrides for the item.
pub async fn learning_object_dates_show_for_courses(configuration: &configuration::Configuration, context_module_id: &str, course_id: &str, include: Option<Vec<String>>, exclude: Option<Vec<String>>, page: Option<i32>, per_page: Option<i32>) -> Result<String, Error<LearningObjectDatesShowForCoursesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_context_module_id = context_module_id;
    let p_path_course_id = course_id;
    let p_query_include = include;
    let p_query_exclude = exclude;
    let p_query_page = page;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/courses/{course_id}/modules/{context_module_id}/date_details", configuration.base_path, context_module_id=crate::apis::urlencode(p_path_context_module_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_exclude {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("exclude".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("exclude", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesShowForCoursesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a learning object's date-related information, including due date, availability dates, override status, and a paginated list of all assignment overrides for the item.
pub async fn learning_object_dates_show_for_courses2(configuration: &configuration::Configuration, assignment_id: &str, course_id: &str, include: Option<Vec<String>>, exclude: Option<Vec<String>>, page: Option<i32>, per_page: Option<i32>) -> Result<String, Error<LearningObjectDatesShowForCourses2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_assignment_id = assignment_id;
    let p_path_course_id = course_id;
    let p_query_include = include;
    let p_query_exclude = exclude;
    let p_query_page = page;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/courses/{course_id}/assignments/{assignment_id}/date_details", configuration.base_path, assignment_id=crate::apis::urlencode(p_path_assignment_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_exclude {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("exclude".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("exclude", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesShowForCourses2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a learning object's date-related information, including due date, availability dates, override status, and a paginated list of all assignment overrides for the item.
pub async fn learning_object_dates_show_for_courses3(configuration: &configuration::Configuration, quiz_id: &str, course_id: &str, include: Option<Vec<String>>, exclude: Option<Vec<String>>, page: Option<i32>, per_page: Option<i32>) -> Result<String, Error<LearningObjectDatesShowForCourses3Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_quiz_id = quiz_id;
    let p_path_course_id = course_id;
    let p_query_include = include;
    let p_query_exclude = exclude;
    let p_query_page = page;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/courses/{course_id}/quizzes/{quiz_id}/date_details", configuration.base_path, quiz_id=crate::apis::urlencode(p_path_quiz_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_exclude {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("exclude".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("exclude", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesShowForCourses3Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a learning object's date-related information, including due date, availability dates, override status, and a paginated list of all assignment overrides for the item.
pub async fn learning_object_dates_show_for_courses4(configuration: &configuration::Configuration, discussion_topic_id: &str, course_id: &str, include: Option<Vec<String>>, exclude: Option<Vec<String>>, page: Option<i32>, per_page: Option<i32>) -> Result<String, Error<LearningObjectDatesShowForCourses4Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_discussion_topic_id = discussion_topic_id;
    let p_path_course_id = course_id;
    let p_query_include = include;
    let p_query_exclude = exclude;
    let p_query_page = page;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/courses/{course_id}/discussion_topics/{discussion_topic_id}/date_details", configuration.base_path, discussion_topic_id=crate::apis::urlencode(p_path_discussion_topic_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_exclude {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("exclude".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("exclude", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesShowForCourses4Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a learning object's date-related information, including due date, availability dates, override status, and a paginated list of all assignment overrides for the item.
pub async fn learning_object_dates_show_for_courses5(configuration: &configuration::Configuration, url_or_id: &str, course_id: &str, include: Option<Vec<String>>, exclude: Option<Vec<String>>, page: Option<i32>, per_page: Option<i32>) -> Result<String, Error<LearningObjectDatesShowForCourses5Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_url_or_id = url_or_id;
    let p_path_course_id = course_id;
    let p_query_include = include;
    let p_query_exclude = exclude;
    let p_query_page = page;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/courses/{course_id}/pages/{url_or_id}/date_details", configuration.base_path, url_or_id=crate::apis::urlencode(p_path_url_or_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_exclude {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("exclude".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("exclude", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesShowForCourses5Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get a learning object's date-related information, including due date, availability dates, override status, and a paginated list of all assignment overrides for the item.
pub async fn learning_object_dates_show_for_courses6(configuration: &configuration::Configuration, attachment_id: &str, course_id: &str, include: Option<Vec<String>>, exclude: Option<Vec<String>>, page: Option<i32>, per_page: Option<i32>) -> Result<String, Error<LearningObjectDatesShowForCourses6Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_attachment_id = attachment_id;
    let p_path_course_id = course_id;
    let p_query_include = include;
    let p_query_exclude = exclude;
    let p_query_page = page;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/courses/{course_id}/files/{attachment_id}/date_details", configuration.base_path, attachment_id=crate::apis::urlencode(p_path_attachment_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_include {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("include".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("include", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_exclude {
        req_builder = match "multi" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("exclude".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("exclude", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesShowForCourses6Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates date-related information for learning objects, including due date, availability dates, override status, and assignment overrides.  Returns 204 No Content response code if successful.
pub async fn learning_object_dates_update_for_courses(configuration: &configuration::Configuration, assignment_id: &str, course_id: &str, learning_object_dates_update_for_courses_request: Option<models::LearningObjectDatesUpdateForCoursesRequest>) -> Result<(), Error<LearningObjectDatesUpdateForCoursesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_assignment_id = assignment_id;
    let p_path_course_id = course_id;
    let p_body_learning_object_dates_update_for_courses_request = learning_object_dates_update_for_courses_request;

    let uri_str = format!("{}/courses/{course_id}/assignments/{assignment_id}/date_details", configuration.base_path, assignment_id=crate::apis::urlencode(p_path_assignment_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_learning_object_dates_update_for_courses_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesUpdateForCoursesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates date-related information for learning objects, including due date, availability dates, override status, and assignment overrides.  Returns 204 No Content response code if successful.
pub async fn learning_object_dates_update_for_courses2(configuration: &configuration::Configuration, quiz_id: &str, course_id: &str, learning_object_dates_update_for_courses_request: Option<models::LearningObjectDatesUpdateForCoursesRequest>) -> Result<(), Error<LearningObjectDatesUpdateForCourses2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_quiz_id = quiz_id;
    let p_path_course_id = course_id;
    let p_body_learning_object_dates_update_for_courses_request = learning_object_dates_update_for_courses_request;

    let uri_str = format!("{}/courses/{course_id}/quizzes/{quiz_id}/date_details", configuration.base_path, quiz_id=crate::apis::urlencode(p_path_quiz_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_learning_object_dates_update_for_courses_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesUpdateForCourses2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates date-related information for learning objects, including due date, availability dates, override status, and assignment overrides.  Returns 204 No Content response code if successful.
pub async fn learning_object_dates_update_for_courses3(configuration: &configuration::Configuration, discussion_topic_id: &str, course_id: &str, learning_object_dates_update_for_courses_request: Option<models::LearningObjectDatesUpdateForCoursesRequest>) -> Result<(), Error<LearningObjectDatesUpdateForCourses3Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_discussion_topic_id = discussion_topic_id;
    let p_path_course_id = course_id;
    let p_body_learning_object_dates_update_for_courses_request = learning_object_dates_update_for_courses_request;

    let uri_str = format!("{}/courses/{course_id}/discussion_topics/{discussion_topic_id}/date_details", configuration.base_path, discussion_topic_id=crate::apis::urlencode(p_path_discussion_topic_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_learning_object_dates_update_for_courses_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesUpdateForCourses3Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates date-related information for learning objects, including due date, availability dates, override status, and assignment overrides.  Returns 204 No Content response code if successful.
pub async fn learning_object_dates_update_for_courses4(configuration: &configuration::Configuration, url_or_id: &str, course_id: &str, learning_object_dates_update_for_courses_request: Option<models::LearningObjectDatesUpdateForCoursesRequest>) -> Result<(), Error<LearningObjectDatesUpdateForCourses4Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_url_or_id = url_or_id;
    let p_path_course_id = course_id;
    let p_body_learning_object_dates_update_for_courses_request = learning_object_dates_update_for_courses_request;

    let uri_str = format!("{}/courses/{course_id}/pages/{url_or_id}/date_details", configuration.base_path, url_or_id=crate::apis::urlencode(p_path_url_or_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_learning_object_dates_update_for_courses_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesUpdateForCourses4Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates date-related information for learning objects, including due date, availability dates, override status, and assignment overrides.  Returns 204 No Content response code if successful.
pub async fn learning_object_dates_update_for_courses5(configuration: &configuration::Configuration, attachment_id: &str, course_id: &str, learning_object_dates_update_for_courses_request: Option<models::LearningObjectDatesUpdateForCoursesRequest>) -> Result<(), Error<LearningObjectDatesUpdateForCourses5Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_attachment_id = attachment_id;
    let p_path_course_id = course_id;
    let p_body_learning_object_dates_update_for_courses_request = learning_object_dates_update_for_courses_request;

    let uri_str = format!("{}/courses/{course_id}/files/{attachment_id}/date_details", configuration.base_path, attachment_id=crate::apis::urlencode(p_path_attachment_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_learning_object_dates_update_for_courses_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<LearningObjectDatesUpdateForCourses5Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

