/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`provisional_grades_bulk_select`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProvisionalGradesBulkSelectError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`provisional_grades_publish`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProvisionalGradesPublishError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`provisional_grades_select`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProvisionalGradesSelectError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`provisional_grades_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProvisionalGradesStatusError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}


/// Choose which provisional grades will be received by associated students for an assignment. The caller must be the final grader for the assignment or an admin with :select_final_grade rights.
pub async fn provisional_grades_bulk_select(configuration: &configuration::Configuration, assignment_id: &str, course_id: &str) -> Result<(), Error<ProvisionalGradesBulkSelectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_assignment_id = assignment_id;
    let p_path_course_id = course_id;

    let uri_str = format!("{}/courses/{course_id}/assignments/{assignment_id}/provisional_grades/bulk_select", configuration.base_path, assignment_id=crate::apis::urlencode(p_path_assignment_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ProvisionalGradesBulkSelectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Publish the selected provisional grade for all submissions to an assignment. Use the \"Select provisional grade\" endpoint to choose which provisional grade to publish for a particular submission.  Students not in the moderation set will have their one and only provisional grade published.  WARNING: This is irreversible. This will overwrite existing grades in the gradebook.
pub async fn provisional_grades_publish(configuration: &configuration::Configuration, assignment_id: &str, course_id: &str) -> Result<(), Error<ProvisionalGradesPublishError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_assignment_id = assignment_id;
    let p_path_course_id = course_id;

    let uri_str = format!("{}/courses/{course_id}/assignments/{assignment_id}/provisional_grades/publish", configuration.base_path, assignment_id=crate::apis::urlencode(p_path_assignment_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ProvisionalGradesPublishError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Choose which provisional grade the student should receive for a submission. The caller must be the final grader for the assignment or an admin with :select_final_grade rights.
pub async fn provisional_grades_select(configuration: &configuration::Configuration, assignment_id: &str, course_id: &str, provisional_grade_id: &str) -> Result<(), Error<ProvisionalGradesSelectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_assignment_id = assignment_id;
    let p_path_course_id = course_id;
    let p_path_provisional_grade_id = provisional_grade_id;

    let uri_str = format!("{}/courses/{course_id}/assignments/{assignment_id}/provisional_grades/{provisional_grade_id}/select", configuration.base_path, assignment_id=crate::apis::urlencode(p_path_assignment_id), course_id=crate::apis::urlencode(p_path_course_id), provisional_grade_id=crate::apis::urlencode(p_path_provisional_grade_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ProvisionalGradesSelectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Tell whether the student's submission needs one or more provisional grades.
pub async fn provisional_grades_status(configuration: &configuration::Configuration, assignment_id: &str, course_id: &str, student_id: Option<i32>) -> Result<(), Error<ProvisionalGradesStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_assignment_id = assignment_id;
    let p_path_course_id = course_id;
    let p_query_student_id = student_id;

    let uri_str = format!("{}/courses/{course_id}/assignments/{assignment_id}/provisional_grades/status", configuration.base_path, assignment_id=crate::apis::urlencode(p_path_assignment_id), course_id=crate::apis::urlencode(p_path_course_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_student_id {
        req_builder = req_builder.query(&[("student_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ProvisionalGradesStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

