/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountNotificationsUpdateRequest {
    /// [String] The role(s) to send global notification to.  Note:  ommitting this field will send to everyone Example:   account_notification_roles: [\"StudentEnrollment\", \"TeacherEnrollment\"]
    #[serde(rename = "account_notification_roles", skip_serializing_if = "Option::is_none")]
    pub account_notification_roles: Option<Vec<String>>,
    #[serde(rename = "account_notification", skip_serializing_if = "Option::is_none")]
    pub account_notification: Option<Box<models::AccountNotificationsUpdateRequestAccountNotification>>,
}

impl AccountNotificationsUpdateRequest {
    pub fn new() -> AccountNotificationsUpdateRequest {
        AccountNotificationsUpdateRequest {
            account_notification_roles: None,
            account_notification: None,
        }
    }
}

