/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnonymousUserDisplay : This mini-object is returned in place of UserDisplay when returning student data for anonymous assignments, and includes an anonymous ID to identify a user within the scope of a single assignment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnonymousUserDisplay {
    /// A unique short ID identifying this user within the scope of a particular assignment.
    #[serde(rename = "anonymous_id", skip_serializing_if = "Option::is_none")]
    pub anonymous_id: Option<String>,
    /// A URL to retrieve a generic avatar.
    #[serde(rename = "avatar_image_url", skip_serializing_if = "Option::is_none")]
    pub avatar_image_url: Option<String>,
    /// The anonymized display name for the student.
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl AnonymousUserDisplay {
    /// This mini-object is returned in place of UserDisplay when returning student data for anonymous assignments, and includes an anonymous ID to identify a user within the scope of a single assignment.
    pub fn new() -> AnonymousUserDisplay {
        AnonymousUserDisplay {
            anonymous_id: None,
            avatar_image_url: None,
            display_name: None,
        }
    }
}

