/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppointmentGroup : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppointmentGroup {
    /// The ID of the appointment group
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The title of the appointment group
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The start of the first time slot in the appointment group
    #[serde(rename = "start_at", skip_serializing_if = "Option::is_none")]
    pub start_at: Option<String>,
    /// The end of the last time slot in the appointment group
    #[serde(rename = "end_at", skip_serializing_if = "Option::is_none")]
    pub end_at: Option<String>,
    /// The text description of the appointment group
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The location name of the appointment group
    #[serde(rename = "location_name", skip_serializing_if = "Option::is_none")]
    pub location_name: Option<String>,
    /// The address of the appointment group's location
    #[serde(rename = "location_address", skip_serializing_if = "Option::is_none")]
    pub location_address: Option<String>,
    /// The number of participant who have reserved slots (see include[] argument)
    #[serde(rename = "participant_count", skip_serializing_if = "Option::is_none")]
    pub participant_count: Option<i32>,
    /// The start and end times of slots reserved by the current user as well as the id of the calendar event for the reservation (see include[] argument)
    #[serde(rename = "reserved_times", skip_serializing_if = "Option::is_none")]
    pub reserved_times: Option<Vec<models::Appointment>>,
    /// Boolean indicating whether observer users should be able to sign-up for an appointment
    #[serde(rename = "allow_observer_signup", skip_serializing_if = "Option::is_none")]
    pub allow_observer_signup: Option<bool>,
    /// The context codes (i.e. courses) this appointment group belongs to. Only people in these courses will be eligible to sign up.
    #[serde(rename = "context_codes", skip_serializing_if = "Option::is_none")]
    pub context_codes: Option<Vec<String>>,
    /// The sub-context codes (i.e. course sections and group categories) this appointment group is restricted to
    #[serde(rename = "sub_context_codes", skip_serializing_if = "Option::is_none")]
    pub sub_context_codes: Option<Vec<i32>>,
    /// Current state of the appointment group ('pending', 'active' or 'deleted'). 'pending' indicates that it has not been published yet and is invisible to participants.
    #[serde(rename = "workflow_state", skip_serializing_if = "Option::is_none")]
    pub workflow_state: Option<WorkflowState>,
    /// Boolean indicating whether the current user needs to sign up for this appointment group (i.e. it's reservable and the min_appointments_per_participant limit has not been met by this user).
    #[serde(rename = "requiring_action", skip_serializing_if = "Option::is_none")]
    pub requiring_action: Option<bool>,
    /// Number of time slots in this appointment group
    #[serde(rename = "appointments_count", skip_serializing_if = "Option::is_none")]
    pub appointments_count: Option<i32>,
    /// Calendar Events representing the time slots (see include[] argument) Refer to the Calendar Events API for more information
    #[serde(rename = "appointments", skip_serializing_if = "Option::is_none")]
    pub appointments: Option<Vec<models::CalendarEvent>>,
    /// Newly created time slots (same format as appointments above). Only returned in Create/Update responses where new time slots have been added
    #[serde(rename = "new_appointments", skip_serializing_if = "Option::is_none")]
    pub new_appointments: Option<Vec<models::CalendarEvent>>,
    /// Maximum number of time slots a user may register for, or null if no limit
    #[serde(rename = "max_appointments_per_participant", skip_serializing_if = "Option::is_none")]
    pub max_appointments_per_participant: Option<i32>,
    /// Minimum number of time slots a user must register for. If not set, users do not need to sign up for any time slots
    #[serde(rename = "min_appointments_per_participant", skip_serializing_if = "Option::is_none")]
    pub min_appointments_per_participant: Option<i32>,
    /// Maximum number of participants that may register for each time slot, or null if no limit
    #[serde(rename = "participants_per_appointment", skip_serializing_if = "Option::is_none")]
    pub participants_per_appointment: Option<i32>,
    /// 'private' means participants cannot see who has signed up for a particular time slot, 'protected' means that they can
    #[serde(rename = "participant_visibility", skip_serializing_if = "Option::is_none")]
    pub participant_visibility: Option<ParticipantVisibility>,
    /// Indicates how participants sign up for the appointment group, either as individuals ('User') or in student groups ('Group'). Related to sub_context_codes (i.e. 'Group' signups always have a single group category)
    #[serde(rename = "participant_type", skip_serializing_if = "Option::is_none")]
    pub participant_type: Option<ParticipantType>,
    /// URL for this appointment group (to update, delete, etc.)
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// URL for a user to view this appointment group
    #[serde(rename = "html_url", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
    /// When the appointment group was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// When the appointment group was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl AppointmentGroup {
    /// 
    pub fn new() -> AppointmentGroup {
        AppointmentGroup {
            id: None,
            title: None,
            start_at: None,
            end_at: None,
            description: None,
            location_name: None,
            location_address: None,
            participant_count: None,
            reserved_times: None,
            allow_observer_signup: None,
            context_codes: None,
            sub_context_codes: None,
            workflow_state: None,
            requiring_action: None,
            appointments_count: None,
            appointments: None,
            new_appointments: None,
            max_appointments_per_participant: None,
            min_appointments_per_participant: None,
            participants_per_appointment: None,
            participant_visibility: None,
            participant_type: None,
            url: None,
            html_url: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// Current state of the appointment group ('pending', 'active' or 'deleted'). 'pending' indicates that it has not been published yet and is invisible to participants.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkflowState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "deleted")]
    Deleted,
}

impl Default for WorkflowState {
    fn default() -> WorkflowState {
        Self::Pending
    }
}
/// 'private' means participants cannot see who has signed up for a particular time slot, 'protected' means that they can
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParticipantVisibility {
    #[serde(rename = "private")]
    Private,
    #[serde(rename = "protected")]
    Protected,
}

impl Default for ParticipantVisibility {
    fn default() -> ParticipantVisibility {
        Self::Private
    }
}
/// Indicates how participants sign up for the appointment group, either as individuals ('User') or in student groups ('Group'). Related to sub_context_codes (i.e. 'Group' signups always have a single group category)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParticipantType {
    #[serde(rename = "User")]
    User,
    #[serde(rename = "Group")]
    Group,
}

impl Default for ParticipantType {
    fn default() -> ParticipantType {
        Self::User
    }
}

