/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarEventsApiSetCourseTimetableRequestTimetables {
    /// [][location_name] [Optional, String] A location name to set for each event
    #[serde(rename = "course_section_id", skip_serializing_if = "Option::is_none")]
    pub course_section_id: Option<String>,
}

impl CalendarEventsApiSetCourseTimetableRequestTimetables {
    pub fn new() -> CalendarEventsApiSetCourseTimetableRequestTimetables {
        CalendarEventsApiSetCourseTimetableRequestTimetables {
            course_section_id: None,
        }
    }
}

