/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentExportsApiCreateForCoursesRequest {
    /// \"common_cartridge\":: Export the contents of the course in the Common Cartridge (.imscc) format \"qti\":: Export quizzes from a course in the QTI format \"zip\":: Export files from a course, group, or user in a zip file
    #[serde(rename = "export_type")]
    pub export_type: ExportType,
    /// Don't send the notifications about the export to the user. Default: false
    #[serde(rename = "skip_notifications", skip_serializing_if = "Option::is_none")]
    pub skip_notifications: Option<bool>,
    /// The select parameter allows exporting specific data. The keys are object types like 'files', 'folders', 'pages', etc. The value for each key is a list of object ids. An id can be an integer or a string.  Multiple object types can be selected in the same call. However, not all object types are valid for every export_type. Common Cartridge supports all object types. Zip and QTI only support the object types as described below.  \"folders\":: Also supported for zip export_type. \"files\":: Also supported for zip export_type. \"quizzes\":: Also supported for qti export_type.
    #[serde(rename = "select", skip_serializing_if = "Option::is_none")]
    pub select: Option<Select>,
}

impl ContentExportsApiCreateForCoursesRequest {
    pub fn new(export_type: ExportType) -> ContentExportsApiCreateForCoursesRequest {
        ContentExportsApiCreateForCoursesRequest {
            export_type,
            skip_notifications: None,
            select: None,
        }
    }
}
/// \"common_cartridge\":: Export the contents of the course in the Common Cartridge (.imscc) format \"qti\":: Export quizzes from a course in the QTI format \"zip\":: Export files from a course, group, or user in a zip file
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExportType {
    #[serde(rename = "common_cartridge")]
    CommonCartridge,
    #[serde(rename = "qti")]
    Qti,
    #[serde(rename = "zip")]
    Zip,
}

impl Default for ExportType {
    fn default() -> ExportType {
        Self::CommonCartridge
    }
}
/// The select parameter allows exporting specific data. The keys are object types like 'files', 'folders', 'pages', etc. The value for each key is a list of object ids. An id can be an integer or a string.  Multiple object types can be selected in the same call. However, not all object types are valid for every export_type. Common Cartridge supports all object types. Zip and QTI only support the object types as described below.  \"folders\":: Also supported for zip export_type. \"files\":: Also supported for zip export_type. \"quizzes\":: Also supported for qti export_type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Select {
    #[serde(rename = "folders")]
    Folders,
    #[serde(rename = "files")]
    Files,
    #[serde(rename = "attachments")]
    Attachments,
    #[serde(rename = "quizzes")]
    Quizzes,
    #[serde(rename = "assignments")]
    Assignments,
    #[serde(rename = "announcements")]
    Announcements,
    #[serde(rename = "calendar_events")]
    CalendarEvents,
    #[serde(rename = "discussion_topics")]
    DiscussionTopics,
    #[serde(rename = "modules")]
    Modules,
    #[serde(rename = "module_items")]
    ModuleItems,
    #[serde(rename = "pages")]
    Pages,
    #[serde(rename = "rubrics")]
    Rubrics,
}

impl Default for Select {
    fn default() -> Select {
        Self::Folders
    }
}

