/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentDetails : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentDetails {
    #[serde(rename = "points_possible", skip_serializing_if = "Option::is_none")]
    pub points_possible: Option<i32>,
    #[serde(rename = "due_at", skip_serializing_if = "Option::is_none")]
    pub due_at: Option<String>,
    #[serde(rename = "unlock_at", skip_serializing_if = "Option::is_none")]
    pub unlock_at: Option<String>,
    #[serde(rename = "lock_at", skip_serializing_if = "Option::is_none")]
    pub lock_at: Option<String>,
    #[serde(rename = "locked_for_user", skip_serializing_if = "Option::is_none")]
    pub locked_for_user: Option<bool>,
    #[serde(rename = "lock_explanation", skip_serializing_if = "Option::is_none")]
    pub lock_explanation: Option<String>,
    #[serde(rename = "lock_info", skip_serializing_if = "Option::is_none")]
    pub lock_info: Option<Box<models::LockInfo>>,
}

impl ContentDetails {
    /// 
    pub fn new() -> ContentDetails {
        ContentDetails {
            points_possible: None,
            due_at: None,
            unlock_at: None,
            lock_at: None,
            locked_for_user: None,
            lock_explanation: None,
            lock_info: None,
        }
    }
}

