/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentSharesAddUsersRequest {
    /// IDs of users to share the content with.
    #[serde(rename = "receiver_ids", skip_serializing_if = "Option::is_none")]
    pub receiver_ids: Option<Vec<String>>,
}

impl ContentSharesAddUsersRequest {
    pub fn new() -> ContentSharesAddUsersRequest {
        ContentSharesAddUsersRequest {
            receiver_ids: None,
        }
    }
}

