/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentImportsCopyCourseContentRequest {
    /// ID or SIS-ID of the course to copy the content from
    #[serde(rename = "source_course", skip_serializing_if = "Option::is_none")]
    pub source_course: Option<String>,
    /// [String, \"course_settings\"|\"assignments\"|\"external_tools\"|\"files\"|\"topics\"|\"calendar_events\"|\"quizzes\"|\"wiki_pages\"|\"modules\"|\"outcomes\"] A list of the course content types to exclude, all areas not listed will be copied.
    #[serde(rename = "except", skip_serializing_if = "Option::is_none")]
    pub except: Option<Vec<String>>,
    /// [String, \"course_settings\"|\"assignments\"|\"external_tools\"|\"files\"|\"topics\"|\"calendar_events\"|\"quizzes\"|\"wiki_pages\"|\"modules\"|\"outcomes\"] A list of the course content types to copy, all areas not listed will not be copied.
    #[serde(rename = "only", skip_serializing_if = "Option::is_none")]
    pub only: Option<Vec<String>>,
}

impl ContentImportsCopyCourseContentRequest {
    pub fn new() -> ContentImportsCopyCourseContentRequest {
        ContentImportsCopyCourseContentRequest {
            source_course: None,
            except: None,
            only: None,
        }
    }
}

