/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextModulesApiCreateRequest {
    #[serde(rename = "module")]
    pub module: Box<models::ContextModulesApiCreateRequestModule>,
}

impl ContextModulesApiCreateRequest {
    pub fn new(module: models::ContextModulesApiCreateRequestModule) -> ContextModulesApiCreateRequest {
        ContextModulesApiCreateRequest {
            module: Box::new(module),
        }
    }
}

