/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConversationsAddMessageRequest {
    /// The message to be sent.
    #[serde(rename = "body")]
    pub body: String,
    /// [String] An array of attachments ids. These must be files that have been previously uploaded to the sender's \"conversation attachments\" folder.
    #[serde(rename = "attachment_ids", skip_serializing_if = "Option::is_none")]
    pub attachment_ids: Option<Vec<String>>,
    /// Media comment id of an audio of video file to be associated with this message.
    #[serde(rename = "media_comment_id", skip_serializing_if = "Option::is_none")]
    pub media_comment_id: Option<String>,
    /// Type of the associated media file.
    #[serde(rename = "media_comment_type", skip_serializing_if = "Option::is_none")]
    pub media_comment_type: Option<MediaCommentType>,
    /// [String]
    #[serde(rename = "recipients", skip_serializing_if = "Option::is_none")]
    pub recipients: Option<Vec<String>>,
    /// [String]
    #[serde(rename = "included_messages", skip_serializing_if = "Option::is_none")]
    pub included_messages: Option<Vec<String>>,
}

impl ConversationsAddMessageRequest {
    pub fn new(body: String) -> ConversationsAddMessageRequest {
        ConversationsAddMessageRequest {
            body,
            attachment_ids: None,
            media_comment_id: None,
            media_comment_type: None,
            recipients: None,
            included_messages: None,
        }
    }
}
/// Type of the associated media file.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaCommentType {
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "video")]
    Video,
}

impl Default for MediaCommentType {
    fn default() -> MediaCommentType {
        Self::Audio
    }
}

