/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoursePacesUpdateRequestSelectedDaysToSkip {
    /// Course pace dates excludes weekends if true
    #[serde(rename = "Array<String>", skip_serializing_if = "Option::is_none")]
    pub array_less_than_string_greater_than: Option<String>,
}

impl CoursePacesUpdateRequestSelectedDaysToSkip {
    pub fn new() -> CoursePacesUpdateRequestSelectedDaysToSkip {
        CoursePacesUpdateRequestSelectedDaysToSkip {
            array_less_than_string_greater_than: None,
        }
    }
}

