/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatedEventData : The created event data object returns all the fields that were set in the format of the following example.  If a field does not exist it was not set. The value of each field changed is in the format of [:old_value, :new_value].  The created event type also includes a created_source field to specify what triggered the creation of the course.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatedEventData {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Vec<String>>,
    #[serde(rename = "start_at", skip_serializing_if = "Option::is_none")]
    pub start_at: Option<Vec<String>>,
    #[serde(rename = "conclude_at", skip_serializing_if = "Option::is_none")]
    pub conclude_at: Option<Vec<String>>,
    #[serde(rename = "is_public", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<Vec<bool>>,
    /// The type of action that triggered the creation of the course.
    #[serde(rename = "created_source", skip_serializing_if = "Option::is_none")]
    pub created_source: Option<String>,
}

impl CreatedEventData {
    /// The created event data object returns all the fields that were set in the format of the following example.  If a field does not exist it was not set. The value of each field changed is in the format of [:old_value, :new_value].  The created event type also includes a created_source field to specify what triggered the creation of the course.
    pub fn new() -> CreatedEventData {
        CreatedEventData {
            name: None,
            start_at: None,
            conclude_at: None,
            is_public: None,
            created_source: None,
        }
    }
}

