/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomColumn : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomColumn {
    /// The ID of the custom gradebook column
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// When true, this column's visibility will be toggled in the Gradebook when a user selects to show or hide notes
    #[serde(rename = "teacher_notes", skip_serializing_if = "Option::is_none")]
    pub teacher_notes: Option<bool>,
    /// header text
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// column order
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    /// won't be displayed if hidden is true
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    /// won't be editable in the gradebook UI
    #[serde(rename = "read_only", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
}

impl CustomColumn {
    /// 
    pub fn new() -> CustomColumn {
        CustomColumn {
            id: None,
            teacher_notes: None,
            title: None,
            position: None,
            hidden: None,
            read_only: None,
        }
    }
}

