/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomGradebookColumnDataApiBulkUpdateRequest {
    /// [Required, Array] Column content. Setting this to an empty string will delete the data object.
    #[serde(rename = "column_data")]
    pub column_data: Vec<String>,
}

impl CustomGradebookColumnDataApiBulkUpdateRequest {
    pub fn new(column_data: Vec<String>) -> CustomGradebookColumnDataApiBulkUpdateRequest {
        CustomGradebookColumnDataApiBulkUpdateRequest {
            column_data,
        }
    }
}

