/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DataServiceSubscription : A subscription to a data service live event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataServiceSubscription {
    /// The id of the context for the subscription.
    #[serde(rename = "ContextId", skip_serializing_if = "Option::is_none")]
    pub context_id: Option<String>,
    /// The type of context for the subscription. Must be 'assignment', or 'root_account'
    #[serde(rename = "ContextType", skip_serializing_if = "Option::is_none")]
    pub context_type: Option<String>,
    /// Array of strings representing the event types for the subscription.
    #[serde(rename = "EventTypes", skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<String>>,
    /// Format to deliver the live events. Must be 'live-event' or 'caliper'.
    #[serde(rename = "Format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    /// An object with a single key: 'Url'.
    #[serde(rename = "TransportMetadata", skip_serializing_if = "Option::is_none")]
    pub transport_metadata: Option<String>,
    /// The type of transport for the event. Must be either 'sqs' or 'https'.
    #[serde(rename = "TransportType", skip_serializing_if = "Option::is_none")]
    pub transport_type: Option<String>,
}

impl DataServiceSubscription {
    /// A subscription to a data service live event.
    pub fn new() -> DataServiceSubscription {
        DataServiceSubscription {
            context_id: None,
            context_type: None,
            event_types: None,
            format: None,
            transport_metadata: None,
            transport_type: None,
        }
    }
}

