/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EPortfolioPage : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EPortfolioPage {
    /// The database ID of the ePortfolio
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The ePortfolio ID to which the entry belongs
    #[serde(rename = "eportfolio_id", skip_serializing_if = "Option::is_none")]
    pub eportfolio_id: Option<i32>,
    /// The positional order of the entry in the list
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    /// The name of the ePortfolio
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The user entered content of the entry
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// The creation timestamp for the ePortfolio
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The timestamp of the last time any of the ePortfolio attributes changed
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl EPortfolioPage {
    /// 
    pub fn new() -> EPortfolioPage {
        EPortfolioPage {
            id: None,
            eportfolio_id: None,
            position: None,
            name: None,
            content: None,
            created_at: None,
            updated_at: None,
        }
    }
}

