/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EnrollmentTermsList : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrollmentTermsList {
    /// a paginated list of all terms in the account
    #[serde(rename = "enrollment_terms", skip_serializing_if = "Option::is_none")]
    pub enrollment_terms: Option<Vec<models::EnrollmentTerm>>,
}

impl EnrollmentTermsList {
    /// 
    pub fn new() -> EnrollmentTermsList {
        EnrollmentTermsList {
            enrollment_terms: None,
        }
    }
}

