/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoldersUpdateRequest {
    /// The new name of the folder
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The id of the folder to move this folder into. The new folder must be in the same context as the original parent folder.
    #[serde(rename = "parent_folder_id", skip_serializing_if = "Option::is_none")]
    pub parent_folder_id: Option<String>,
    /// The datetime to lock the folder at
    #[serde(rename = "lock_at", skip_serializing_if = "Option::is_none")]
    pub lock_at: Option<String>,
    /// The datetime to unlock the folder at
    #[serde(rename = "unlock_at", skip_serializing_if = "Option::is_none")]
    pub unlock_at: Option<String>,
    /// Flag the folder as locked
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    /// Flag the folder as hidden
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    /// Set an explicit sort position for the folder
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
}

impl FoldersUpdateRequest {
    pub fn new() -> FoldersUpdateRequest {
        FoldersUpdateRequest {
            name: None,
            parent_folder_id: None,
            lock_at: None,
            unlock_at: None,
            locked: None,
            hidden: None,
            position: None,
        }
    }
}

