/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GradingRules : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GradingRules {
    /// Number of lowest scores to be dropped for each user.
    #[serde(rename = "drop_lowest", skip_serializing_if = "Option::is_none")]
    pub drop_lowest: Option<i32>,
    /// Number of highest scores to be dropped for each user.
    #[serde(rename = "drop_highest", skip_serializing_if = "Option::is_none")]
    pub drop_highest: Option<i32>,
    /// Assignment IDs that should never be dropped.
    #[serde(rename = "never_drop", skip_serializing_if = "Option::is_none")]
    pub never_drop: Option<Vec<i32>>,
}

impl GradingRules {
    /// 
    pub fn new() -> GradingRules {
        GradingRules {
            drop_lowest: None,
            drop_highest: None,
            never_drop: None,
        }
    }
}

