/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupCategoriesCreateForAccountsRequestSplitGroupCount {
    /// Create this number of groups, and evenly distribute students among them. not allowed with \"enable_self_signup\". because the group assignment happens synchronously, it's recommended that you instead use the assign_unassigned_members endpoint. (Course Only)
    #[serde(rename = "Deprecated", skip_serializing_if = "Option::is_none")]
    pub deprecated: Option<String>,
}

impl GroupCategoriesCreateForAccountsRequestSplitGroupCount {
    pub fn new() -> GroupCategoriesCreateForAccountsRequestSplitGroupCount {
        GroupCategoriesCreateForAccountsRequestSplitGroupCount {
            deprecated: None,
        }
    }
}

