/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataSaxDocApiUpdateRequest {
    /// The new display name of the file, with a limit of 255 characters.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The id of the folder to move this file into. The new folder must be in the same context as the original parent folder. If the file is in a context without folders this does not apply.
    #[serde(rename = "parent_folder_id", skip_serializing_if = "Option::is_none")]
    pub parent_folder_id: Option<String>,
    /// If the file is moved to a folder containing a file with the same name, or renamed to a name matching an existing file, the API call will fail unless this parameter is supplied.  \"overwrite\":: Replace the existing file with the same name \"rename\":: Add a qualifier to make the new filename unique
    #[serde(rename = "on_duplicate", skip_serializing_if = "Option::is_none")]
    pub on_duplicate: Option<OnDuplicate>,
    /// The datetime to lock the file at
    #[serde(rename = "lock_at", skip_serializing_if = "Option::is_none")]
    pub lock_at: Option<String>,
    /// The datetime to unlock the file at
    #[serde(rename = "unlock_at", skip_serializing_if = "Option::is_none")]
    pub unlock_at: Option<String>,
    /// Flag the file as locked
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    /// Flag the file as hidden
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    /// Configure which roles can access this file
    #[serde(rename = "visibility_level", skip_serializing_if = "Option::is_none")]
    pub visibility_level: Option<String>,
}

impl MetadataSaxDocApiUpdateRequest {
    pub fn new() -> MetadataSaxDocApiUpdateRequest {
        MetadataSaxDocApiUpdateRequest {
            name: None,
            parent_folder_id: None,
            on_duplicate: None,
            lock_at: None,
            unlock_at: None,
            locked: None,
            hidden: None,
            visibility_level: None,
        }
    }
}
/// If the file is moved to a folder containing a file with the same name, or renamed to a name matching an existing file, the API call will fail unless this parameter is supplied.  \"overwrite\":: Replace the existing file with the same name \"rename\":: Add a qualifier to make the new filename unique
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnDuplicate {
    #[serde(rename = "overwrite")]
    Overwrite,
    #[serde(rename = "rename")]
    Rename,
}

impl Default for OnDuplicate {
    fn default() -> OnDuplicate {
        Self::Overwrite
    }
}

