/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutcomeGroupsApiUpdateOtherRequest {
    /// The new outcome group title.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The new outcome group description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A custom GUID for the learning standard.
    #[serde(rename = "vendor_guid", skip_serializing_if = "Option::is_none")]
    pub vendor_guid: Option<String>,
    /// The id of the new parent outcome group.
    #[serde(rename = "parent_outcome_group_id", skip_serializing_if = "Option::is_none")]
    pub parent_outcome_group_id: Option<i32>,
}

impl OutcomeGroupsApiUpdateOtherRequest {
    pub fn new() -> OutcomeGroupsApiUpdateOtherRequest {
        OutcomeGroupsApiUpdateOtherRequest {
            title: None,
            description: None,
            vendor_guid: None,
            parent_outcome_group_id: None,
        }
    }
}

