/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Permission : A permission that can be granted to a role
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Permission {
    /// The API identifier for the permission
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The human-readable label for the permission
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// The group this permission belongs to, if it is part of a granular permission group
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// The human-readable label for the group this permission belongs to
    #[serde(rename = "group_label", skip_serializing_if = "Option::is_none")]
    pub group_label: Option<String>,
    /// The base role types this permission can be enabled for
    #[serde(rename = "available_to", skip_serializing_if = "Option::is_none")]
    pub available_to: Option<Vec<String>>,
    /// The base role types this permission is enabled for by default
    #[serde(rename = "true_for", skip_serializing_if = "Option::is_none")]
    pub true_for: Option<Vec<String>>,
}

impl Permission {
    /// A permission that can be granted to a role
    pub fn new() -> Permission {
        Permission {
            key: None,
            label: None,
            group: None,
            group_label: None,
            available_to: None,
            true_for: None,
        }
    }
}

