/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Poll {
    /// The unique identifier for the poll.
    #[serde(rename = "id")]
    pub id: i32,
    /// The question/title of the poll.
    #[serde(rename = "question")]
    pub question: String,
    /// A short description of the poll.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The time at which the poll was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The unique identifier for the user that created the poll.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// An aggregate of the results of all associated poll sessions, with the poll choice id as the key, and the aggregated submission count as the value.
    #[serde(rename = "total_results", skip_serializing_if = "Option::is_none")]
    pub total_results: Option<serde_json::Value>,
}

impl Poll {
    pub fn new(id: i32, question: String) -> Poll {
        Poll {
            id,
            question,
            description: None,
            created_at: None,
            user_id: None,
            total_results: None,
        }
    }
}

