/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Progress : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Progress {
    /// the ID of the Progress object
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// the context owning the job.
    #[serde(rename = "context_id", skip_serializing_if = "Option::is_none")]
    pub context_id: Option<i32>,
    #[serde(rename = "context_type", skip_serializing_if = "Option::is_none")]
    pub context_type: Option<String>,
    /// the id of the user who started the job
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// the type of operation
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    /// percent completed
    #[serde(rename = "completion", skip_serializing_if = "Option::is_none")]
    pub completion: Option<i32>,
    /// the state of the job one of 'queued', 'running', 'completed', 'failed'
    #[serde(rename = "workflow_state", skip_serializing_if = "Option::is_none")]
    pub workflow_state: Option<WorkflowState>,
    /// the time the job was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// the time the job was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// optional details about the job
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// optional results of the job. omitted when job is still pending
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<serde_json::Value>,
    /// url where a progress update can be retrieved
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl Progress {
    /// 
    pub fn new() -> Progress {
        Progress {
            id: None,
            context_id: None,
            context_type: None,
            user_id: None,
            tag: None,
            completion: None,
            workflow_state: None,
            created_at: None,
            updated_at: None,
            message: None,
            results: None,
            url: None,
        }
    }
}
/// the state of the job one of 'queued', 'running', 'completed', 'failed'
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkflowState {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for WorkflowState {
    fn default() -> WorkflowState {
        Self::Queued
    }
}

