/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PseudonymsUpdateRequestLogin {
    /// [String] The new unique ID for the login.
    #[serde(rename = "unique_id", skip_serializing_if = "Option::is_none")]
    pub unique_id: Option<String>,
    /// [String] The new password for the login. Admins can only set a password for another user if the \"Password setting by admins\" account setting is enabled.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// [String] The prior password for the login. Required if the caller is changing their own password.
    #[serde(rename = "old_password")]
    pub old_password: String,
    /// [String] SIS ID for the login. To set this parameter, the caller must be able to manage SIS permissions on the account.
    #[serde(rename = "sis_user_id", skip_serializing_if = "Option::is_none")]
    pub sis_user_id: Option<String>,
    /// [String] Integration ID for the login. To set this parameter, the caller must be able to manage SIS permissions on the account. The Integration ID is a secondary identifier useful for more complex SIS integrations.
    #[serde(rename = "integration_id", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<String>,
    /// [String] The authentication provider this login is associated with. Logins associated with a specific provider can only be used with that provider. Legacy providers (LDAP, CAS, SAML) will search for logins associated with them, or unassociated logins. New providers will only search for logins explicitly associated with them. This can be the integer ID of the provider, or the type of the provider (in which case, it will find the first matching provider). To unassociate from a known provider, specify null or an empty string.
    #[serde(rename = "authentication_provider_id", skip_serializing_if = "Option::is_none")]
    pub authentication_provider_id: Option<String>,
    /// [String, \"active\"|\"suspended\"] Used to suspend or re-activate a login.
    #[serde(rename = "workflow_state", skip_serializing_if = "Option::is_none")]
    pub workflow_state: Option<WorkflowState>,
    /// [String] The declared intention of the user type. This can be set, but does not change any Canvas functionality with respect to their access. A user can still be a teacher, admin, student, etc. in any particular context without regard to this setting. This can be used for administrative purposes for integrations to be able to more easily identify why the user was created. Valid values are:   * administrative   * observer   * staff   * student   * student_other   * teacher
    #[serde(rename = "declared_user_type", skip_serializing_if = "Option::is_none")]
    pub declared_user_type: Option<String>,
}

impl PseudonymsUpdateRequestLogin {
    pub fn new(old_password: String) -> PseudonymsUpdateRequestLogin {
        PseudonymsUpdateRequestLogin {
            unique_id: None,
            password: None,
            old_password,
            sis_user_id: None,
            integration_id: None,
            authentication_provider_id: None,
            workflow_state: None,
            declared_user_type: None,
        }
    }
}
/// [String, \"active\"|\"suspended\"] Used to suspend or re-activate a login.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkflowState {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
}

impl Default for WorkflowState {
    fn default() -> WorkflowState {
        Self::Active
    }
}

