/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PseudonymsCreateRequestLogin {
    /// [Required, String] The unique ID for the new login.
    #[serde(rename = "unique_id")]
    pub unique_id: String,
    /// [String] The new login's password.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// [String] SIS ID for the login. To set this parameter, the caller must be able to manage SIS permissions on the account.
    #[serde(rename = "sis_user_id", skip_serializing_if = "Option::is_none")]
    pub sis_user_id: Option<String>,
    /// [String] Integration ID for the login. To set this parameter, the caller must be able to manage SIS permissions on the account. The Integration ID is a secondary identifier useful for more complex SIS integrations.
    #[serde(rename = "integration_id", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<String>,
    /// [String] The authentication provider this login is associated with. Logins associated with a specific provider can only be used with that provider. Legacy providers (LDAP, CAS, SAML) will search for logins associated with them, or unassociated logins. New providers will only search for logins explicitly associated with them. This can be the integer ID of the provider, or the type of the provider (in which case, it will find the first matching provider).
    #[serde(rename = "authentication_provider_id", skip_serializing_if = "Option::is_none")]
    pub authentication_provider_id: Option<String>,
    /// [String] The declared intention of the user type. This can be set, but does not change any Canvas functionality with respect to their access. A user can still be a teacher, admin, student, etc. in any particular context without regard to this setting. This can be used for administrative purposes for integrations to be able to more easily identify why the user was created. Valid values are:   * administrative   * observer   * staff   * student   * student_other   * teacher
    #[serde(rename = "declared_user_type", skip_serializing_if = "Option::is_none")]
    pub declared_user_type: Option<String>,
}

impl PseudonymsCreateRequestLogin {
    pub fn new(unique_id: String) -> PseudonymsCreateRequestLogin {
        PseudonymsCreateRequestLogin {
            unique_id,
            password: None,
            sis_user_id: None,
            integration_id: None,
            authentication_provider_id: None,
            declared_user_type: None,
        }
    }
}

