/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuizSubmission {
    /// The ID of the quiz submission.
    #[serde(rename = "id")]
    pub id: i64,
    /// The ID of the Quiz the quiz submission belongs to.
    #[serde(rename = "quiz_id")]
    pub quiz_id: i64,
    /// The ID of the Student that made the quiz submission.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    /// The ID of the Submission the quiz submission represents.
    #[serde(rename = "submission_id", skip_serializing_if = "Option::is_none")]
    pub submission_id: Option<i64>,
    /// The time at which the student started the quiz submission.
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    /// The time at which the student submitted the quiz submission.
    #[serde(rename = "finished_at", skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<String>,
    /// The time at which the quiz submission will be overdue, and be flagged as a late submission.
    #[serde(rename = "end_at", skip_serializing_if = "Option::is_none")]
    pub end_at: Option<String>,
    /// For quizzes that allow multiple attempts, this field specifies the quiz submission attempt number.
    #[serde(rename = "attempt", skip_serializing_if = "Option::is_none")]
    pub attempt: Option<i64>,
    /// Number of times the student was allowed to re-take the quiz over the multiple-attempt limit.
    #[serde(rename = "extra_attempts", skip_serializing_if = "Option::is_none")]
    pub extra_attempts: Option<i64>,
    /// Amount of extra time allowed for the quiz submission, in minutes.
    #[serde(rename = "extra_time", skip_serializing_if = "Option::is_none")]
    pub extra_time: Option<i64>,
    /// The student can take the quiz even if it's locked for everyone else
    #[serde(rename = "manually_unlocked", skip_serializing_if = "Option::is_none")]
    pub manually_unlocked: Option<bool>,
    /// Amount of time spent, in seconds.
    #[serde(rename = "time_spent", skip_serializing_if = "Option::is_none")]
    pub time_spent: Option<i64>,
    /// The score of the quiz submission, if graded.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<i64>,
    /// The original score of the quiz submission prior to any re-grading.
    #[serde(rename = "score_before_regrade", skip_serializing_if = "Option::is_none")]
    pub score_before_regrade: Option<i64>,
    /// For quizzes that allow multiple attempts, this is the score that will be used, which might be the score of the latest, or the highest, quiz submission.
    #[serde(rename = "kept_score", skip_serializing_if = "Option::is_none")]
    pub kept_score: Option<i64>,
    /// Number of points the quiz submission's score was fudged by.
    #[serde(rename = "fudge_points", skip_serializing_if = "Option::is_none")]
    pub fudge_points: Option<i64>,
    /// Whether the student has viewed their results to the quiz.
    #[serde(rename = "has_seen_results", skip_serializing_if = "Option::is_none")]
    pub has_seen_results: Option<bool>,
    /// The current state of the quiz submission. Possible values: ['untaken'|'pending_review'|'complete'|'settings_only'|'preview'].
    #[serde(rename = "workflow_state", skip_serializing_if = "Option::is_none")]
    pub workflow_state: Option<String>,
    /// Indicates whether the quiz submission is overdue and needs submission
    #[serde(rename = "overdue_and_needs_submission", skip_serializing_if = "Option::is_none")]
    pub overdue_and_needs_submission: Option<bool>,
}

impl QuizSubmission {
    pub fn new(id: i64, quiz_id: i64) -> QuizSubmission {
        QuizSubmission {
            id,
            quiz_id,
            user_id: None,
            submission_id: None,
            started_at: None,
            finished_at: None,
            end_at: None,
            attempt: None,
            extra_attempts: None,
            extra_time: None,
            manually_unlocked: None,
            time_spent: None,
            score: None,
            score_before_regrade: None,
            kept_score: None,
            fudge_points: None,
            has_seen_results: None,
            workflow_state: None,
            overdue_and_needs_submission: None,
        }
    }
}

