/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Role : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Role {
    /// The id of the role
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The label of the role.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// The label of the role. (Deprecated alias for 'label')
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// The role type that is being used as a base for this role. For account-level roles, this is 'AccountMembership'. For course-level roles, it is an enrollment type.
    #[serde(rename = "base_role_type", skip_serializing_if = "Option::is_none")]
    pub base_role_type: Option<String>,
    /// Whether this role applies to account memberships (i.e., not linked to an enrollment in a course).
    #[serde(rename = "is_account_role", skip_serializing_if = "Option::is_none")]
    pub is_account_role: Option<bool>,
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<Box<models::Account>>,
    /// The state of the role: 'active', 'inactive', or 'built_in'
    #[serde(rename = "workflow_state", skip_serializing_if = "Option::is_none")]
    pub workflow_state: Option<String>,
    /// The date and time the role was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The date and time the role was last updated.
    #[serde(rename = "last_updated_at", skip_serializing_if = "Option::is_none")]
    pub last_updated_at: Option<String>,
    /// A dictionary of permissions keyed by name (see 'List assignable permissions' API).
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<serde_json::Value>,
}

impl Role {
    /// 
    pub fn new() -> Role {
        Role {
            id: None,
            label: None,
            role: None,
            base_role_type: None,
            is_account_role: None,
            account: None,
            workflow_state: None,
            created_at: None,
            last_updated_at: None,
            permissions: None,
        }
    }
}

