/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchableAccount : A minimal representation of an Account for Canvas Apps search purposes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchableAccount {
    /// The Canvas DB ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The account name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The SIS ID of the account, if any. Only present if user can read or manage SIS.
    #[serde(rename = "sis_id", skip_serializing_if = "Option::is_none")]
    pub sis_id: Option<String>,
    /// Names of the accounts in this account's hierarchy, excluding the root and this account.
    #[serde(rename = "display_path", skip_serializing_if = "Option::is_none")]
    pub display_path: Option<Vec<String>>,
}

impl SearchableAccount {
    /// A minimal representation of an Account for Canvas Apps search purposes
    pub fn new() -> SearchableAccount {
        SearchableAccount {
            id: None,
            name: None,
            sis_id: None,
            display_path: None,
        }
    }
}

