/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Section : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Section {
    /// The unique identifier for the section.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of the section.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The sis id of the section. This field is only included if the user has permission to view SIS information.
    #[serde(rename = "sis_section_id", skip_serializing_if = "Option::is_none")]
    pub sis_section_id: Option<String>,
    /// Optional: The integration ID of the section. This field is only included if the user has permission to view SIS information.
    #[serde(rename = "integration_id", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<String>,
    /// The unique identifier for the SIS import if created through SIS. This field is only included if the user has permission to manage SIS information.
    #[serde(rename = "sis_import_id", skip_serializing_if = "Option::is_none")]
    pub sis_import_id: Option<i32>,
    /// The unique Canvas identifier for the course in which the section belongs
    #[serde(rename = "course_id", skip_serializing_if = "Option::is_none")]
    pub course_id: Option<i32>,
    /// The unique SIS identifier for the course in which the section belongs. This field is only included if the user has permission to view SIS information.
    #[serde(rename = "sis_course_id", skip_serializing_if = "Option::is_none")]
    pub sis_course_id: Option<String>,
    /// the start date for the section, if applicable
    #[serde(rename = "start_at", skip_serializing_if = "Option::is_none")]
    pub start_at: Option<String>,
    /// the end date for the section, if applicable
    #[serde(rename = "end_at", skip_serializing_if = "Option::is_none")]
    pub end_at: Option<String>,
    /// Restrict user enrollments to the start and end dates of the section
    #[serde(rename = "restrict_enrollments_to_section_dates", skip_serializing_if = "Option::is_none")]
    pub restrict_enrollments_to_section_dates: Option<bool>,
    /// The unique identifier of the original course of a cross-listed section
    #[serde(rename = "nonxlist_course_id", skip_serializing_if = "Option::is_none")]
    pub nonxlist_course_id: Option<i32>,
    /// optional: the total number of active and invited students in the section
    #[serde(rename = "total_students", skip_serializing_if = "Option::is_none")]
    pub total_students: Option<i32>,
    /// optional: A list of students that are included in the section. Returned only if include[]=students. WARNING: this collection's size is capped (if there are an extremely large number of users in the section (thousands) not all of them will be returned). If you need to capture all the users in a section with certainty or experiencing slow response consider using the paginated /api/v1/sections/<section_id>/users endpoint.
    #[serde(rename = "students", skip_serializing_if = "Option::is_none")]
    pub students: Option<Vec<models::User>>,
}

impl Section {
    /// 
    pub fn new() -> Section {
        Section {
            id: None,
            name: None,
            sis_section_id: None,
            integration_id: None,
            sis_import_id: None,
            course_id: None,
            sis_course_id: None,
            start_at: None,
            end_at: None,
            restrict_enrollments_to_section_dates: None,
            nonxlist_course_id: None,
            total_students: None,
            students: None,
        }
    }
}

