/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SisImportsApiCreateRequestPreAttachment {
    /// [String] The name of the file to be uploaded in a separate request via the {file:file.file_uploads.html File Upload} workflow. Do not supply +attachment+ when using this option. This option decouples the file upload from the SIS import request, which can improve reliability with larger files.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// [String] Other file upload properties; see {file:file.file_uploads.html File Upload Documentation}
    #[serde(rename = "*", skip_serializing_if = "Option::is_none")]
    pub star: Option<String>,
}

impl SisImportsApiCreateRequestPreAttachment {
    pub fn new() -> SisImportsApiCreateRequestPreAttachment {
        SisImportsApiCreateRequestPreAttachment {
            name: None,
            star: None,
        }
    }
}

