/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdatedEventData : The updated event data object returns all the fields that have changed in the format of the following example.  If a field does not exist it was not changed.  The value is an array that contains the before and after values for the change as in [:old_value, :new_value].
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatedEventData {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Vec<String>>,
    #[serde(rename = "start_at", skip_serializing_if = "Option::is_none")]
    pub start_at: Option<Vec<String>>,
    #[serde(rename = "conclude_at", skip_serializing_if = "Option::is_none")]
    pub conclude_at: Option<Vec<String>>,
    #[serde(rename = "is_public", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<Vec<bool>>,
}

impl UpdatedEventData {
    /// The updated event data object returns all the fields that have changed in the format of the following example.  If a field does not exist it was not changed.  The value is an array that contains the before and after values for the change as in [:old_value, :new_value].
    pub fn new() -> UpdatedEventData {
        UpdatedEventData {
            name: None,
            start_at: None,
            conclude_at: None,
            is_public: None,
        }
    }
}

