/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageRightsSetUsageRightsForCoursesRequestUsageRights {
    /// [Required, String, \"own_copyright\"|\"used_by_permission\"|\"fair_use\"|\"public_domain\"|\"creative_commons\"] The intellectual property justification for using the files in Canvas
    #[serde(rename = "use_justification")]
    pub use_justification: UseJustification,
    /// [Optional, String] The legal copyright line for the files
    #[serde(rename = "legal_copyright", skip_serializing_if = "Option::is_none")]
    pub legal_copyright: Option<String>,
    /// [Optional, String] The license that applies to the files. See the {api:UsageRightsController#licenses List licenses endpoint} for the supported license types.
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
}

impl UsageRightsSetUsageRightsForCoursesRequestUsageRights {
    pub fn new(use_justification: UseJustification) -> UsageRightsSetUsageRightsForCoursesRequestUsageRights {
        UsageRightsSetUsageRightsForCoursesRequestUsageRights {
            use_justification,
            legal_copyright: None,
            license: None,
        }
    }
}
/// [Required, String, \"own_copyright\"|\"used_by_permission\"|\"fair_use\"|\"public_domain\"|\"creative_commons\"] The intellectual property justification for using the files in Canvas
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UseJustification {
    #[serde(rename = "own_copyright")]
    OwnCopyright,
    #[serde(rename = "used_by_permission")]
    UsedByPermission,
    #[serde(rename = "fair_use")]
    FairUse,
    #[serde(rename = "public_domain")]
    PublicDomain,
    #[serde(rename = "creative_commons")]
    CreativeCommons,
}

impl Default for UseJustification {
    fn default() -> UseJustification {
        Self::OwnCopyright
    }
}

