/*
 * Canvas LMS API
 *
 * Canvas LMS REST API - Generated from YARD documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserDisplay : This mini-object is used for secondary user responses, when we just want to provide enough information to display a user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserDisplay {
    /// The ID of the user.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// A short name the user has selected, for use in conversations or other less formal places through the site.
    #[serde(rename = "short_name", skip_serializing_if = "Option::is_none")]
    pub short_name: Option<String>,
    /// If avatars are enabled, this field will be included and contain a url to retrieve the user's avatar.
    #[serde(rename = "avatar_image_url", skip_serializing_if = "Option::is_none")]
    pub avatar_image_url: Option<String>,
    /// URL to access user, either nested to a context or directly.
    #[serde(rename = "html_url", skip_serializing_if = "Option::is_none")]
    pub html_url: Option<String>,
}

impl UserDisplay {
    /// This mini-object is used for secondary user responses, when we just want to provide enough information to display a user.
    pub fn new() -> UserDisplay {
        UserDisplay {
            id: None,
            short_name: None,
            avatar_image_url: None,
            html_url: None,
        }
    }
}

